theme: 'readthedocs'
site_name: Cosmic Craft Creative Guide
pages:
  - 'Main Page': 'index.md'
  - 'Preface': 'preface/index.md'
  - 'I. Introduction': 'introduction/index.md'
  - 'II. Commands':
    - 'commands/index.md'
    - 'Basics': 'commands/basics.md'
    - 'Plotting': 'commands/plotting.md'
    - 'Disguise': 'commands/disguise.md'
    - 'Donator': 'commands/donator.md'
repo_name: 'GitHub'
repo_url: 'https://github.com/Hans5958/cc-creative-guide'
