theme: 'readthedocs'
site_name: 'Cosmic Craft Creative Guide'
site_description: 'Guide for Creative on Cosmic Craft. Every aspect explained.'
site_author: 'Hans5958'
site_url: 'https://hans5958.github.io/cc-creative-guide'
pages:
  - 'Main Page': 'index.md'
  - 'Preface': 'preface/index.md'
  - 'I. Introduction': 'introduction/index.md'
  - 'II. Commands':
    - 'Index': 'commands/index.md'
    - 'Basics': 'commands/basics.md'
    - 'Plotting': 'commands/plotting.md'
    - 'Disguise': 'commands/disguise.md'
    - 'Marriage': 'commands/marriage.md'
    - 'Donator': 'commands/donator.md'
  - 'III. Things To Know':
    - 'Index': 'things/index.md'
    - 'Donator Ranks': 'things/donator.md'
    - 'Cheating and Hacking': 'things/cheat.md'
    - 'Reboot': 'things/reboot.md'
    - 'Color and Formatting Codes': 'things/format.md'
    - 'Plot Music ID': 'things/musicid.md'
    - 'Plugins': 'things/plugins.md'
    - 'Voting': 'things/voting.md'
    - 'WorldEdit': 'things/worldedit.md'
  - 'Ending': 'ending/index.md'
  - 'Credits': 'credits/index.md'
google_analytics: ['UA-49890594-3', 'auto']
repo_name: 'GitHub'
repo_url: 'https://github.com/Hans5958/cc-creative-guide'
